//
//  Capitals.swift
//  Apple Pie (UIKit)
//
//  Created by Fedor Boretskiy on 05.03.2022.
//

extension GuessingCollection {
    static let capitals = GuessingCollection(
        hintTypeDescription: "🏳️",
        list: [
//            WordToGuess(word: "Тирана", info: "Столица Албании", hint: "🇦🇱"),
//            WordToGuess(word: "Алжир", info: "Столица Алжира", hint: "🇩🇿"),
//            WordToGuess(word: "Андорра-ла-Велья", info: "Столица Андорры", hint: "🇦🇩"),
//            WordToGuess(word: "Луанда", info: "Столица Анголы", hint: "🇦🇴"),
//            WordToGuess(word: "Сент-Джонс", info: "Столица Антигуа и Барбуда", hint: "🇦🇬"),
//            WordToGuess(word: "Буэнос-Айрес", info: "Столица Аргентины", hint: "🇦🇷"),
//            WordToGuess(word: "Ереван", info: "Столица Армении", hint: "🇦🇲"),
//            WordToGuess(word: "Канберра", info: "Столица Австралии", hint: "🇦🇺"),
//            WordToGuess(word: "Вена", info: "Столица Австрии", hint: "🇦🇹"),
//            WordToGuess(word: "Баку", info: "Столица Азербайджана", hint: "🇦🇿"),
//            WordToGuess(word: "Нассау", info: "Столица Багамских Островов (полная официальная форма — Содружество Багамских Островов)", hint: "🇧🇸"),
//            WordToGuess(word: "Манама", info: "Столица Бахрейна", hint: "🇧🇭"),
//            WordToGuess(word: "Дакка", info: "Столица Бангладеша", hint: "🇧🇩"),
//            WordToGuess(word: "Бриджтаун", info: "Столица Барбадоса", hint: "🇧🇧"),
//            WordToGuess(word: "Минск", info: "Столица Белоруссии", hint: "🇧🇾"),
//            WordToGuess(word: "Брюссель", info: "Столица Бельгии", hint: "🇧🇪"),
//            WordToGuess(word: "Бельмопан", info: "Столица Белиза", hint: "🇧🇿"),
//            WordToGuess(word: "Порто-Ново", info: "Столица Бенина", hint: "🇧🇯"),
//            WordToGuess(word: "Тхимпху", info: "Столица Бутана", hint: "🇧🇹"),
//            WordToGuess(word: "Сукре", info: "Столица  Боливии", hint: "🇧🇴"),
//            WordToGuess(word: "Сараево", info: "Столица Боснии и Герцеговины", hint: "🇧🇦"),
//            WordToGuess(word: "Габороне", info: "Столица Ботсвана", hint: "🇧🇼"),
//            WordToGuess(word: "Бразилиа", info: "Столица Бразилии", hint: "🇧🇷"),
//            WordToGuess(word: "Бандар-Сери-Бегаван", info: "Столица Брунея", hint: "🇧🇳"),
//            WordToGuess(word: "София", info: "Столица Болгарии", hint: "🇧🇬"),
//            WordToGuess(word: "Уагадугу", info: "Столица Буркина-Фасо", hint: "🇧🇫"),
//            WordToGuess(word: "Гитега", info: "Столица Бурунди", hint: "🇧🇮"),
//            WordToGuess(word: "Пномпень", info: "Столица Камбоджи (ранее Кампучия)", hint: "🇰🇭"),
//            WordToGuess(word: "Яунде", info: "Столица Камеруна", hint: "🇨🇲"),
//            WordToGuess(word: "Оттава", info: "Столица Канады", hint: "🇨🇦"),
            WordToGuess(word: "Прая", info: "Столица Кабо-Верде", hint: "🇨🇻"),
            WordToGuess(word: "Банги", info: "Столица ЦАР (Центральноафриканская Республика, иногда просто Центральная Африка)", hint: "🇨🇫"),
            WordToGuess(word: "Нджамена", info: "Столица Республики Чад", hint: "🇹🇩"),
            WordToGuess(word: "Сантьяго", info: "Столица Чили", hint: "🇨🇱"),
            WordToGuess(word: "Пекин", info: "Столица Китая", hint: "🇨🇳"),
            WordToGuess(word: "Богота", info: "Столица Колумбии", hint: "🇨🇴"),
            WordToGuess(word: "Морони", info: "Столица Комор (официальное название — Союз Коморских Островов", hint: "🇰🇲"),
            WordToGuess(word: "Браззавиль", info: "Столица Республики Конго", hint: "🇨🇬"),
            WordToGuess(word: "Киншаса", info: "Столица Демократической Республики Конго", hint: "🇨🇩"),
            WordToGuess(word: "Сан-Хосе", info: "Столица Коста-Рики", hint: "🇨🇷"),
            WordToGuess(word: "Ямусукро", info: "Столица Кот-д’Ивуара", hint: "🇨🇮"),
            WordToGuess(word: "Загреб", info: "Столица Хорватии", hint: "🇭🇷"),
            WordToGuess(word: "Гавана", info: "Столица Кубы", hint: "🇨🇺"),
            WordToGuess(word: "Никосия", info: "Столица Кипра", hint: "🇨🇾"),
            WordToGuess(word: "Прага", info: "Столица Чехии", hint: "🇨🇿"),
            WordToGuess(word: "Копенгаген", info: "Столица Дании", hint: "🇩🇰"),
            WordToGuess(word: "Джибути", info: "Столица Джибути", hint: "🇩🇯"),
            WordToGuess(word: "Розо", info: "Столица Содружества Доминики", hint: "🇩🇲"),
            WordToGuess(word: "Санто-Доминго", info: "Столица Доминиканской Республики", hint: "🇩🇴"),
            WordToGuess(word: "Кито", info: "Столица Эквадора", hint: "🇪🇨"),
            WordToGuess(word: "Каир", info: "Столица Египта", hint: "🇪🇬"),
            WordToGuess(word: "Сан-Сальвадор", info: "Столица Сальвадора", hint: "🇸🇻"),
            WordToGuess(word: "Малабо", info: "Столица Экваториальной Гвинеи", hint: "🇬🇶"),
            WordToGuess(word: "Асмэра", info: "Столица Эритреи", hint: "🇪🇷"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
//            //
//            WordToGuess(word: "XXX", info: "Столица XXX", hint: "🏳️"),
        ]
        )
}
